package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;
import javajdbctut1.Javajdbc;

public class addempController {
	@FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	@FXML
	private TextField id;
	@FXML
	private TextField name;
	@FXML
	private TextField position;
	@FXML
	private TextField salary;
	@FXML
	private TextField age;
	@FXML
	private TextField gender;

	// Event Listener on Button.onAction
	@FXML
	public void back(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("ManageEmployee.fxml"));
		 root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                 scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	 stage.show();	
	}
	// Event Listener on Button.onAction
	@FXML
	public void apply(ActionEvent event)throws IOException {
		// TODO Autogenerated
		String Id = id.getText();
		String Name = name.getText();
		String Pos = position.getText();
		String Sal = salary.getText();
		String Age = age.getText();
		String Gend = gender.getText();
                
                int id=Integer.parseInt(Id);
                int sal=Integer.parseInt(Sal);
                int age=Integer.parseInt(Age);
                
                   String branchid=Javajdbc. holdbranch;
                Manager.insertemployee(id, Name, Pos, sal, age, Gend,branchid);
                FXMLLoader loader=new FXMLLoader(getClass().getResource("ManageEmployee.fxml"));
		 root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                 scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	         stage.show();	
	}
}
