package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;


public class AllempDetailController {
	@FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	// Event Listener on Button.onAction
            void func(Scene scene1) {
		    scene=scene1;
		}
	@FXML
	public void back(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("EmpDetail.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
                 scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 scene = new Scene(root);
		 stage.setScene(scene);
	 stage.show();
	}
}
