package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.RadioButton;
import javafx.stage.Stage;

public class BillController extends Employee{
	@FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	@FXML
	private Label cname;
	@FXML
	private Label amt;
       
    String amount;
	String goglename;
	String phone;
	// Event Listener on RadioButton.onAction
            void func(Scene scene1) {
		    scene=scene1;
		}
	@FXML
	public void setname(String name) {
		goglename=name;
		cname.setText("Customer Name: "+name);
	}
	public void setphone(String name) {
		phone=name;
//		cname.setText("Phone number: "+name);
	}
        int paytype;
	void setamount(String amounts) {
	    amount=amounts;
		amt.setText(amount);
	}
	public void cashpay(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("finalBill.fxml"));
		root=loader.load();
                paytype=0;
		finalBillController own=loader.getController();
		System.out.println(goglename+"billpay");
		own.setName(goglename);
		own.setPhone(phone);
                own.setamount(amount);
                own.setpaytype(paytype);
        
            System.out.println("in billcontroller employee.addcustomer");
            Employee.AddCustomer(amount);
            
            
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
                
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	 stage.show();		
	}
        public void Cardpay(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("finalBill.fxml"));
		root=loader.load();
                paytype=1;
		finalBillController own=loader.getController();
		System.out.println(goglename+"billpay");
		own.setName(goglename);
		own.setPhone(phone);
                own.setamount(amount);
                own.setpaytype(paytype);
        
        
            System.out.println("in billcontroller employee.addcustomer");
            Employee.AddCustomer(amount);
            
            
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	 stage.show();		
	}
        public void Netpay(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("finalBill.fxml"));
		root=loader.load();
                paytype=2;
		finalBillController own=loader.getController();
		System.out.println(goglename+"billpay");
		own.setName(goglename);
		own.setPhone(phone);
                own.setamount(amount);
                own.setpaytype(paytype);
        
            System.out.println("in billcontroller employee.addcustomer");
            Employee.AddCustomer(amount);
            
            
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	 stage.show();		
	}
        public void Upipay(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("finalBill.fxml"));
		root=loader.load();
                paytype=3;
		finalBillController own=loader.getController();
		System.out.println(goglename+"billpay");
		own.setName(goglename);
		own.setPhone(phone);
                own.setamount(amount);
                own.setpaytype(paytype);
        
            System.out.println("in billcontroller employee.addcustomer");
            Employee.AddCustomer(amount);
            
            
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	 stage.show();		
	}
	// Event Listener on RadioButton.onAction
	// Event Listener on Button.onAction
	@FXML
	public void back(ActionEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader(getClass().getResource("GetfinalBill.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	 stage.show();		
	}
}
