package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class BillpayController {
	@FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	@FXML
	private TextField amt;
	@FXML
	private Label ph;
	@FXML
	private Label cname;
String Name;
String Ph;
    void func(Scene scene1) {
		    scene=scene1;
		}
	// Event Listener on Button.onAction
	@FXML
	
	public void setname(String name) {
		Name=name;
		 cname.setText("Customer Name: "+name);
	}
	public void setphone(String phone) {
		Ph=phone; 
		ph.setText("phone number: "+phone);
	}
	
	public void recipe(ActionEvent event) throws IOException {
		// TODO Autogenerated
		String amount = amt.getText();
		FXMLLoader loader=new FXMLLoader(getClass().getResource("finalBill.fxml"));
		root=loader.load();
		finalBillController own=loader.getController();
		own.setamount(amount);
		own.setName(Name);
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	 stage.show();
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void back(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("Bill.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	 stage.show();		
	}
}
