package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;
import javajdbctut1.Javajdbc;

public class DeleteempController extends Employee{
	@FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	@FXML
	private TextField id;
    void func(Scene scene1) {
		    scene=scene1;
		}
	// Event Listener on Button.onAction
	@FXML
	public void back(ActionEvent event) throws IOException {
				FXMLLoader loader=new FXMLLoader(getClass().getResource("ManageEmployee.fxml"));
				root=loader.load();
				 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
				 scene = new Scene(root);
                                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
				 stage.setScene(scene);
			 stage.show();	
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void delete(ActionEvent event)throws IOException {
		// TODO Autogenerated
		String Id = id.getText();
                
                int id=Integer.parseInt(Id);
                
                String branchid=Javajdbc.holdbranch;
                Manager.deleteemployee(id,branchid);
                FXMLLoader loader=new FXMLLoader(getClass().getResource("ManageEmployee.fxml"));
				root=loader.load();
				 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
				 scene = new Scene(root);
                                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
				 stage.setScene(scene);
			 stage.show();	
                
	}
}
