package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.scene.control.TextField;
import javajdbctut1.Javajdbc;

public class EmployeeserachController {
    @FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
        @FXML 
        private TextField nameemp;
        @FXML 
        private TextField saleemp;
	// Event Listener on Button.onAction
            void func(Scene scene1) {
		    scene=scene1;
		}
	@FXML
	public void back(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("Empdetail.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	 stage.show();	
	}
        @FXML
	public void getall(ActionEvent event)
        {
            // TODO Autogenerated
            String branchid=Javajdbc. holdbranch;
            Manager.show_all(branchid);
	}
	// Event Listener on RadioButton.onAction
	@FXML
	public void getnameemp(ActionEvent event)
        {
            String namejd=nameemp.getText();
            String branchid=Javajdbc. holdbranch;
            System.out.println(namejd);
            Manager.showalldetailspartialstring(namejd,branchid);
	}
        @FXML
	public void getsalemp(ActionEvent event)
        {
            String saljd=saleemp.getText();
            String branchid=Javajdbc. holdbranch;
            System.out.println(saljd);
            Manager.showallgreaterthan(saljd, branchid);
	}

    
}
