package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.control.RadioButton;
import javajdbctut1.Javajdbc;

public class ManageEcoController {

    @FXML
    private Stage stage;
    @FXML
    private Scene scene;
    @FXML
    private Parent root;
    @FXML
    private Label inownlab;
    @FXML
    private Label proownlab;
    @FXML
    private Label exownlab;
    @FXML
    private RadioButton inco;
    @FXML
    private RadioButton pro;
    @FXML
    private RadioButton exp;

    // Event Listener on RadioButton.onAction
    @FXML
    public void incomeown(ActionEvent event) {
        System.out.println("in incomeown manageecocontroller");

        if (inco.isSelected()) {
            int income = Javajdbc.sumparticularrow("income");
            String incomejd = String.valueOf(income);
            String disincome = "Business income is :" + incomejd;
            inownlab.setText(disincome);
        } else {
            inownlab.setText("");
        }
        // TODO Autogenerated
    }
    // Event Listener on RadioButton.onAction

    @FXML
    public void profitown(ActionEvent event) {
        System.out.println("in profitown manageecocontroller");
        if (pro.isSelected()) {
            int profitjd = Javajdbc.sumparticularrow("profit");
            String disprofit = "Business profit is :" + profitjd;

            proownlab.setText(disprofit);

        } else {
            proownlab.setText("");
        }
        // TODO Autogenerated
    }
    // Event Listener on RadioButton.onAction

    @FXML
    public void expensesown(ActionEvent event) {
        // TODO Autogenerated
        System.out.println("in expenseown manageecocontroller");

        if (exp.isSelected()) {
            int exjd = Javajdbc.sumparticularrow("expenses");
            String disex = "Business expense is :" + exjd;

            exownlab.setText(disex);

        } else {
            exownlab.setText("");
        }
    }
    // Event Listener on RadioButton.onAction
//	@FXML
//	public void payment_archieves(ActionEvent event) {
//		// TODO Autogenerated
//	}
//	// Event Listener on Button.onAction

    @FXML
    public void back(ActionEvent event) throws IOException {
        // TODO Autogenerated
        FXMLLoader loader = new FXMLLoader(getClass().getResource("owner.fxml"));
        root = loader.load();
        stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        scene = new Scene(root);
         scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
        stage.setScene(scene);
        stage.show();
    }
}
