package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.control.RadioButton;
import javajdbctut1.Javajdbc;

public class ManageEconomyController {

    @FXML
    private Stage stage;
    @FXML
    private Scene scene;
    @FXML
    private Parent root;
    @FXML
    private Label incomelab;
    @FXML
    private Label expenseslab;
    @FXML
    private Label profitlab;
    @FXML
    private RadioButton inco;
    @FXML
    private RadioButton pro;
    @FXML
    private RadioButton exp;
    // Event Listener on Button.onAction

    @FXML
    public void back(ActionEvent event) throws IOException {
        // TODO Autogenerated
        FXMLLoader loader = new FXMLLoader(getClass().getResource("manager.fxml"));
        root = loader.load();
        stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        scene = new Scene(root);
         scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
        stage.setScene(scene);
        stage.show();
    }

    @FXML
    public void showincome(ActionEvent event) {
        //jdbc se sring me bharo
        System.out.println("in showincome of manageeconomycontroller");

        if (inco.isSelected()) {
            String incomejd = String.valueOf(Javajdbc.sumparticularrowbybranch("Income", Javajdbc.holdbranch));
            String disincome = "Branch income is :" + incomejd;
            incomelab.setText(disincome);
        } else {
            incomelab.setText("");
        }
//		FXMLLoader loader=new FXMLLoader(getClass().getResource("ManageEmployee.fxml"));
//		root=loader.load();
//		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
//		 scene = new Scene(root);
//		 stage.setScene(scene);
//		 stage.show();'

    }

    public void showexpenses(ActionEvent event) {

        if (exp.isSelected()) {
            String expensejd = String.valueOf(Javajdbc.sumparticularrowbybranch("Expenses", Javajdbc.holdbranch));
            String disexpense = "Branch expenses are :" + expensejd;

            expenseslab.setText(disexpense);
        } else {
            expenseslab.setText("");
        }
//		FXMLLoader loader=new FXMLLoader(getClass().getResource("ManageEmployee.fxml"));
//		root=loader.load();
//		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
//		 scene = new Scene(root);
//		 stage.setScene(scene);
//		 stage.show();

    }

    public void showprofit(ActionEvent event) {

//		FXMLLoader loader=new FXMLLoader(getClass().getResource("ManageEmployee.fxml"));
//		root=loader.load();
//		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
//		 scene = new Scene(root);
//		 stage.setScene(scene);
//		 stage.show();
        if (pro.isSelected()) {

            String profitjd = String.valueOf(Javajdbc.sumparticularrowbybranch("Profit", Javajdbc.holdbranch));
            String disprofit = "Branch profit is :" + profitjd;
            profitlab.setText(disprofit);

        } else {
            profitlab.setText("");
        }

    }

}
