/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javajdbctut1.Javajdbc;

public class newbramanController {

    private static void createmanager(String mname, String salary, String gender, String age,String managerid) {
        System.out.println("in createmanager in newbramancontroller");
        Connection con = Javajdbc.getConnection("oopsproject", "root", "dhruv");
        try {
            PreparedStatement st = con.prepareStatement("insert into Manager values(?,?,?,?,?,?)");
              st.setInt(1  , parseInt(managerid));
              st.setString(2, mname);
              st.setInt(3, parseInt(salary));
              st.setInt(4, parseInt(age));
              st.setString(5,gender);
              st.setInt(6,parseInt(Javajdbc.holdbranchidinowner));
              Javajdbc.allbranchid.add(Javajdbc.holdbranchidinowner);
              Javajdbc.allmanagerid.add(managerid);
            int row = st.executeUpdate();
            System.out.println(row+" row/s inserted in manager");
        } catch (SQLException ex) {
           
    }
    }

    @FXML
    private Stage stage;
    @FXML
    private Scene scene;
    @FXML
    private Parent root;
    @FXML
    private TextField manid;
    @FXML
    private TextField name;
    @FXML
    private TextField sal;
    @FXML
    private TextField gen;
    @FXML
    private TextField age;
    @FXML 
    private Label badcred;

    @FXML
    public void bramancrea(ActionEvent event) throws IOException {
        // TODO Autogenerated

        String managerid = manid.getText();
        //if else from array list
        //int val = Javajdbc.StringExists(managerid);
        int val=Main.StringExists(managerid, Javajdbc.allmanagerid);
        if (val == 0) {
            String mname = name.getText();
            String sala = sal.getText();
            String gender = gen.getText();
            String ager = age.getText();
            newbramanController.createmanager(mname,sala,gender,ager,managerid);
            FXMLLoader loader = new FXMLLoader(getClass().getResource("ManageBranch.fxml"));
            root = loader.load();
            stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
            scene = new Scene(root);
             scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
            stage.setScene(scene);
            stage.show();
        }
        else{
        	badcred.setText("The Manager id is existing ....try another");
        }

    }

}
