package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;
import static java.lang.Integer.parseInt;

import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javajdbctut1.Javajdbc;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
public class newbranchController {

    private static void createbranch(String brId, String cname, String address) {
        System.out.println("in createbranch");
        Connection con = Javajdbc.getConnection("oopsproject", "root", "dhruv");
        try {
            PreparedStatement st = con.prepareStatement("insert into Branch values(?,?,?)");
            st.setInt(1, parseInt(brId));
            st.setString(2, cname);
            st.setString(3,address);
            int row = st.executeUpdate();
            System.out.println(row+" row/s inserted in branch");
        } catch (SQLException ex) {
            System.out.println("Excpetion in createbranch in newbranchController");
    }

    }

    @FXML
    private Stage stage;
    @FXML
    private Scene scene;
    @FXML
    private Parent root;
    @FXML
    private TextField brid;
    @FXML
    private TextField city;
    @FXML
    //private TextField position;
    //@FXML
    private TextField add;
    @FXML
    private Label badcred;

    @FXML
    public void back(ActionEvent event) throws IOException {
        // TODO Autogenerated
        FXMLLoader loader = new FXMLLoader(getClass().getResource("ManageBranch.fxml"));
        root = loader.load();
        stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        scene = new Scene(root);
         scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
        stage.setScene(scene);
        stage.show();
    }
    @FXML
    	public void managerassign(ActionEvent event) throws IOException{
            System.out.println("in managerassign new branchcontroller");
            String brId = brid.getText();
            int val=Main.StringExists(brId, Javajdbc.allbranchid);
    	if(val==0) {
// TODO Autogenerated
                String cname = city.getText();
		String  address= add.getText();
                
                Javajdbc.holdbranchidinowner=brId;
                newbranchController.createbranch(brId,cname,address);
                FXMLLoader loader=new FXMLLoader(getClass().getResource("newbraman.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	        stage.show();	
		
	}
    	else{
    		badcred.setText("The Branch id is existing ....try another");
    	}

}
}
//
//package application;
//
//import javafx.fxml.FXML;
//import javafx.fxml.FXMLLoader;
//import javafx.scene.Node;
//import javafx.scene.Parent;
//import javafx.scene.Scene;
//import javafx.stage.Stage;
//
//import java.io.IOException;
//
//import javafx.event.ActionEvent;
//import javafx.scene.control.Label;
//import javafx.scene.control.TextField;
//
//public class newbranchController {
//
//    @FXML
//    private Stage stage;
//    @FXML
//    private Scene scene;
//    @FXML
//    private Parent root;
//    @FXML
//    private TextField brid;
//    @FXML
//    private TextField city;
//    @FXML
//    //private TextField position;
//    //@FXML
//    private TextField add;
//    @FXML 
//    private Label badcred;
//
//    @FXML
//    public void back(ActionEvent event) throws IOException {
//        // TODO Autogenerated
//        FXMLLoader loader = new FXMLLoader(getClass().getResource("ManageBranch.fxml"));
//        root = loader.load();
//        stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
//        scene = new Scene(root);
//        stage.setScene(scene);
//        stage.show();
//    }
//    @FXML
//	public void managerassign(ActionEvent event) throws IOException{
//    	
//		// TODO Autogenerated
//    	int val=1;
//    	if(val==1) {
//    		String brId = brid.getText();
//    		String cname = city.getText();
//    		//String Pos = position.getText();
//    		String  address= add.getText();
//                    FXMLLoader loader=new FXMLLoader(getClass().getResource("newbraman.fxml"));
//    		root=loader.load();
//    		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
//    		 scene = new Scene(root);
//    		 stage.setScene(scene);
//    	        stage.show();	
//    		
//    	}
//    	else {
//    		badcred.setText("The Branch id is existing ....try another");
//    	}
//		
//	}
//
//}
//
//
