package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class NewManagerController {
	@FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	@FXML
	private TextField id;
	@FXML
	private TextField name;
	@FXML
	private TextField position;
	@FXML
	private TextField salary;
	@FXML
	private TextField age;
	@FXML
	private TextField gender;

	// Event Listener on Button.onAction
	@FXML
	public void back(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("Managemanage.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
		 stage.setScene(scene);
	 stage.show();	
	}
	// Event Listener on Button.onAction
	@FXML
	public void apply(ActionEvent event) {
		// TODO Autogenerated
		String Id = id.getText();
		String Name = name.getText();
		String Pos = position.getText();
		String Sal = salary.getText();
		String Ag_e = age.getText();
		String Gend = gender.getText();
	}
}
