package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javajdbctut1.Javajdbc;

public class optionController extends Javajdbc {

    @FXML
    private Stage stage;
    @FXML
    private Scene scene;
    @FXML
    private Parent root;
    @FXML
    private TextField uname;
    @FXML
    private TextField psd;
    @FXML
    private Button submit;
    @FXML
    private Label cr;

        void func(Scene scene1) {
		    scene=scene1;
		}
    // Event Listener on Button[#submit].onAction
    @FXML
    public void role(ActionEvent event) throws IOException {
        // TODO Autogenerated
//		String name = uname.getText();
        System.out.println("in role of optionController");


        String p = psd.getText();
        String pass = p.substring(0, 1);
        String branch = p.substring(2);
        if(!(branch.equals("0000")))
         Javajdbc.holdbranchdetails(branch);

        //holding the branch in javajdbc hold branch
        System.out.println("Calling holdbranchdetails of javajdbc");

        if (pass.equals("e") && (branch.equals("8572") || branch.equals("8672") || branch.equals("8752") || branch.equals("8681"))) {

            FXMLLoader loader = new FXMLLoader(getClass().getResource("employee.fxml"));
            root = loader.load();
            
            stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
            scene = new Scene(root);
            scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
            stage.setScene(scene);
            stage.show();
        } else if (pass.equals("m") && (branch.equals("8572") || branch.equals("8672") || branch.equals("8752") || branch.equals("8681"))) {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("manager.fxml"));
            root = loader.load();
//			payedController own=loader.getController();
//			own.displaybill(amount);
//			own.phno(ph);
            stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
            scene = new Scene(root);
            scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
            stage.setScene(scene);
            stage.show();
        } else if (pass.equals("o") && (branch.equals("0000"))) {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("owner.fxml"));
            root = loader.load();
//			payedController own=loader.getController();
//			own.displaybill(amount);
//			own.phno(ph);
            stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
            scene = new Scene(root);
            scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
            stage.setScene(scene);
            stage.show();

        } else {
            cr.setText("Wrong Credentials");
            uname.clear();
            psd.clear();

        }

    }
}
