package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.stage.Stage;

public class SeeOrderController extends Employee{
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	@FXML
	private Label id1;
	@FXML
	private Label id2;
	@FXML
	private Label id3;
	@FXML
	private Label id4;
	@FXML
	private Label id5;
	@FXML
	private Label id6;
	@FXML
	private Label id7;
	@FXML
	private Label id8;
	@FXML
	private Label id9;
	@FXML
	private Label id10;
	@FXML
	private Label totalid;
        
 
	 String totalstr;
	
	// Event Listener on Button.onAction
	private String[] menu= {"Momos","Burger","Pasta","Salad","Patties","Chicken Lollipop","Chicken Roll","Shwarma","Omlet","Egg Sandwich"
			,"Paneer","Dal Makhni","Rajma","Chole Bhatoore","Naan Bread","Butter Chicken","Mutton","Egg Curry","Fish Delight","Biryani"
			,"GulabJamun","Falooda","Choco Brownie","Fudge","Shahi Kheer","Coffee","Mocktail","Arabian Delight","Jaljira","Cold Cola"};
	private int[] price={150,100,250,175,50,200,100,300,150,200,200,200,100,200,100,200,300,250,200,250,100,100,250,200,200,200,200,200,200,50};
void func(int arr[]) {
	 int k=1;
	 int total=0;
	 for(int i=0;i<30;i++) {
		 if(arr[i]==1) {
			 String tag=menu[i]+"   "+price[i];
			 total=total+price[i];
			 //id1.setText(tag);
			 switch(k) {
			    case 1:
			    	id1.setText(tag);
			    	k++;
			    	break;
			    case  2:
			    	id2.setText(tag);
			    	k++;
			    	break;
			    case 3:
			    	id3.setText(tag);
			    	k++;
			    	break;
			    case 4:
			    	id4.setText(tag);
			    	k++;
			    	break;
			    case 5:
			    	id5.setText(tag);
			    	k++;
			    	break;
			    case 6:
			    	id6.setText(tag);
			    	k++;
			    	break;
			    case 7:
			    	id7.setText(tag);
			    	k++;
			    	break;
			    case 8:
			    	id8.setText(tag);
			    	k++;
			    	break;
			    case 9:
			    	id9.setText(tag);
			    	k++;
			    	break;
			    case 10:
			    	id10.setText(tag);
			    	k++;
			    	break;
			 }
			 
		 }
		 
	 totalstr=""+total;
	 totalid.setText(totalstr);
       
}
}

	@FXML
	public void place(ActionEvent event) throws IOException {
            
//            System.out.println("hel");
//            System.out.println(totalamount);
         
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("GetfinalBill.fxml"));
		root=loader.load();
		GetfinalBillController own=loader.getController();
		own.setamount(totalstr);
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
              
		 stage.show();	
	}
	// Event Listener on Button.onAction
	@FXML
	public void back(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("TakeOrd.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
		 stage.show();	
	}
}
