package application;
import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
public class StartController{
	    @FXML
	    private Stage stage;
	    @FXML
	    private Scene scene;
	    @FXML
	    private Parent root;
        @FXML
        private AnchorPane anchor;
	    
	    void func(Scene scene1) {
			System.out.printf("Hi\n");
		    scene=scene1;
		}
	@FXML
	public void getstart(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("option.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
//		 scene = new Scene(root);
		 scene.setRoot(root);
		 anchor.setLayoutY(100);
		 //stage.setFullScreen(true);
                 scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	         stage.show();	
	}
	
     
      
}
