package application;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;
import javajdbctut1.Javajdbc;



public class takedownbranchController {
    @FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	// Event Listener on Button.onAction
        @FXML
        private TextField brid;
        @FXML
        private Label badcred;
	@FXML
	public void back(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("owner.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                 scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	 stage.show();	
	}
        public void takebranch(ActionEvent event) throws IOException {
		// TODO Autogenerated
                String Brid=brid.getText();
             
                int val= Main.StringExists(Brid,  Javajdbc.allbranchid);
                if(val==1){
                //takedownbranch here
                owner.takedownbranch(Brid);
		FXMLLoader loader=new FXMLLoader(getClass().getResource("ManageBranch.fxml"));
		root=loader.load();
		stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
                scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		stage.setScene(scene);
	        stage.show();
                }
                else{
                    badcred.setText("Branch Id entered is wrong");
                }
	}
    
}
