package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class TakeOrderController {

	// Event Listener on RadioButton.onAction
	@FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	@FXML
	public void showmenu(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("Showmenu.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
		 stage.show();	
	}
	// Event Listener on RadioButton.onAction
	@FXML
	public void additem(ActionEvent event) throws IOException {
		FXMLLoader loader=new FXMLLoader(getClass().getResource("AddItem.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
		 stage.show();		
	}
	// Event Listener on RadioButton.onAction
	//@FXML
//	public void getfinalbill(ActionEvent event) throws IOException {
//		FXMLLoader loader=new FXMLLoader(getClass().getResource("GetfinalBill.fxml"));
//		root=loader.load();
//		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
//		 scene = new Scene(root);
//		 stage.setScene(scene);
//		 stage.show();	
//	}
	// Event Listener on RadioButton.onAction
	@FXML
	public void recievePayment(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("GetfinalBill.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
		 stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void back(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("employee.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
		 stage.show();	
	}
}

