package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class UpadateManagerController extends owner{
	@FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	@FXML
	private TextField id;
	@FXML
	private TextField name;
	@FXML
	//private TextField position;
	//@FXML
	private TextField salary;
	@FXML
	private TextField age;
	@FXML
	private TextField gender;

	// Event Listener on Button.onAction
	@FXML
	public void back(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("owner.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	 stage.show();	
	}
	// Event Listener on Button.onAction
	@FXML
	public void apply(ActionEvent event) throws IOException{
		// TODO Autogenerated
                System.out.println("in upadatemanagercontroller");
		String Id = id.getText();
		String Name = name.getText();
		//String Pos = position.getText();
		String Sal = salary.getText();
		String Age = age.getText();
		String Gend = gender.getText();
                
                owner.update_manager(Id,Name,Sal,Age,Gend);
                
                FXMLLoader loader=new FXMLLoader(getClass().getResource("owner.fxml"));
		root=loader.load();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
                  scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		 stage.setScene(scene);
	        stage.show();	
		
	}
}
