//package application;
//
//import javafx.fxml.FXML;
//
//import javafx.scene.control.TextField;
//
//import javafx.event.ActionEvent;
//
//public class billpayedController {
//	@FXML
//	private TextField ph_no;
//	@FXML
//	private TextField amt;
//
//	// Event Listener on Button.onAction
//	@FXML
//	public void recipe(ActionEvent event) {
//		// TODO Autogenerated
//	}
//}
package javajdbctut1;

import java.io.IOException;
import java.sql.SQLException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class billpayedController {
	@FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	@FXML
	private TextField ph_no;
	@FXML
	private TextField amt;

	// Event Listener on Button.onAction
	@FXML
	public void recipe(ActionEvent event) throws IOException, SQLException {
		// TODO Autogenerated
		String amount = amt.getText();
		String ph=ph_no.getText();
		FXMLLoader loader=new FXMLLoader(getClass().getResource("payed.fxml"));
		root=loader.load();
		payedController own=loader.getController();
		own.displaybill(amount);
		own.phno(ph);
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
		 stage.setScene(scene);
	 stage.show();	
	}
}