package javajdbctut1;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import java.sql.*;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

public class payedController {
	@FXML
	private Stage stage;
	@FXML
	private Scene scene;
	@FXML
	private Parent root;
	@FXML
	private Label ph;
	@FXML
	private Label stars;
	@FXML
	private Label amt;

	// Event Listener on Button.onAction
	@FXML
	public void displaybill(String amount) {
		 amt.setText("Amount payed: "+amount);
		 Integer i=Integer.valueOf(amount);
		 Integer k=i/1000;
	     stars.setText("Stars earned: "+k);

	}
	public void phno(String phno) throws SQLException {
		ph.setText("phone number: "+phno);
             Connection con  = ConnectionProvider.getConnection("oopsproject" ,"root","dhruv" );
             System.out.println(con);
             Statement st=Javajdbc.get_a_fresh_statement(con);
                  ResultSet tabledetails = st.executeQuery(Javajdbc.alltablevaluesQuery("points"));  
	         boolean searchval=Javajdbc.searchemployee(tabledetails, "phno", phno);
                 System.out.println(searchval);
        }
	public void returnmenu(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader=new FXMLLoader(getClass().getResource("bill.fxml"));
		root=loader.load();
		billController own=loader.getController();
		 stage=(Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
		 stage.setScene(scene);
	 stage.show();	
	}
}
